ParisEntreAmis/Models/Bet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ParisEntreAmis.Models
{
    public class Bet
    {
        public int BetID { get; set; }

        public bool CalculateNormalScore { get; set; }

        public DateTime DeadLine { get; set; }

        public DateTime CreatedOn { get; set; }

        public string Comment { get; set; }

        public int MatchID { get; set; }

        [ForeignKey("MatchID")]
        public virtual Match Match { get; set; }

        public int CircleID { get; set; }

        [ForeignKey("CircleID")]
        public virtual BetCircle Circle { get; set; }

        public virtual User User { get; set; }
        
        [NotMapped]
        public bool IsClosed { get { return DeadLine <= DateTime.Now.AddHours(1); } }
    }
}

ParisEntreAmis/Controllers/BetCircleController.cs
using ParisEntreAmis.Models;
using ParisEntreAmis.Repository;
using ParisEntreAmis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParisEntreAmis.Controllers
{
    [Authorize]
    public class BetCircleController : BaseController
    {

        private BetCircleService circleService = new BetCircleService();
        private BetService betService = new BetService();
        private MatchService matchService = new MatchService();


        //
        // GET: /BetCircle/

        public ActionResult Index()
        {
            
            return View(circleService.GetAll());
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BetCircle b)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    User usr =null;

                    var repo = new UserRepository();
                   
                    usr  = repo.GetByUsername(User.Identity.Name);
                    

                    if (usr == null)
                        throw new Exception("Bad user");

                    circleService.Create(b, usr);
                    return RedirectToAction("Edit", new { id = b.BetCircleID });
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("",ex.Message);

                }
            }


            return View(b);
        }

        public ActionResult Details(int id) 
        {
            User usr = null;

            var repo = new UserRepository();
           
            usr = repo.GetByUsername(User.Identity.Name);
           

            if (usr == null)
                throw new Exception("Bad user");

            BetCircle betSet = this.circleService.Get(id,usr);

            if (betSet == null)
            {
                return HttpNotFound();
            }


            var tokenGenerator = new Firebase.TokenGenerator("3BNGwIhvAPAfIJIZLANvdsiwgOuAR1lfQtnYORaE");
            var authPayload = new Dictionary<string, object>()
            {                
                { "Username" , usr.Username },
                { "circleID" , betSet.BetCircleID .ToString()}
            };

            string token = tokenGenerator.CreateToken(authPayload);

            ViewBag.firebaseToken = token;

            return View(this.circleService.InitBetCircleViewModel(betSet, usr));

        }


        public ActionResult Edit(int id)
        {
            User usr = null;

            var repo = new UserRepository();

            usr = repo.GetByUsername(User.Identity.Name);


            if (usr == null)
                throw new Exception("Bad user");

            BetCircle betSet = this.circleService.GetForAdministration(id, usr);

            if (betSet == null)
            {
                return HttpNotFound();
            }

            return View(this.circleService.InitEditModel(betSet));

        }

        public ActionResult DisplayBetsAvailableInCategory(int BetCircleID , string CodeCategory)
        {
            User usr = null;

            var repo = new UserRepository();

            usr = repo.GetByUsername(User.Identity.Name);

            BetCircle circle = this.circleService.GetForAdministration(BetCircleID, usr);
            if (circle == null)
            {
                return HttpNotFound();
            }


            BetsAvailableForCircleEditModel res = this.circleService.GetAvailableBetsInCategory(circle, CodeCategory);

            return PartialView("_AddBetToCircle", res);

        }


        //
        // GET: /Bet/

        public ActionResult AddMatchToCircle(int MatchID, int CircleID)
        {


            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }


            BetCircle betSet = circleService.GetForAdministration(CircleID, user);

            if (betSet == null)
            {
                return HttpNotFound();
            }


            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }

            Bet bet = betService.Create(match, betSet);

            return PartialView("_EditBetsInCircle", bet);
        }


        public ActionResult RemoveMatchFromCircle(int MatchID, int CircleID)
        {

            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            BetCircle betSet = circleService.GetForAdministration(CircleID, user);

            if (betSet == null)
            {
                return HttpNotFound();
            }

            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }


            int betIdDeleted = circleService.RemoveMatchFromCircle(match, betSet);


            return Json(betIdDeleted, JsonRequestBehavior.AllowGet);
        }


        public ActionResult RemoveBetFromCircle(int BetID, int MatchID)
        {
            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            Bet bet = betService.GetForAdministration(BetID, user);

            if (bet == null)
            {
                return HttpNotFound();
            }

            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }

            betService.Delete(bet);

            return Json(0, JsonRequestBehavior.AllowGet);
        }


        public ActionResult JoinCircle(string circleGuid)
        {
            User user = new UserService().GetCurrentUser();

            ConfirmJoinCircle vm = new ConfirmJoinCircle();

            BetCircle circle = this.circleService.GetCircleByGuid(circleGuid);

            if (circle == null)
            {
                return HttpNotFound();
            }

            vm.BetCircle = circle;
            vm.Status = this.circleService.DoesUserCanJoinCircle(circle, user);


            return View(vm);
        }

        public ActionResult ConfirmJoinCircle(string circleGuid)
        {
            
            User user = new UserService().GetCurrentUser();

            ConfirmJoinCircle vm = new ConfirmJoinCircle();

            BetCircle circle = this.circleService.GetCircleByGuid(circleGuid);

            if (circle == null)
            {
                return HttpNotFound();
            }

            vm.BetCircle = circle;
            vm.Status = this.circleService.DoesUserCanJoinCircle(circle, user);


            if (vm.Status == CanPeopleJoinCircle.Yes)
            {
                //on ajoute le user et on le redirige vers le cercle
                this.circleService.AddUserToCircle(user.UserID, circle);

                return RedirectToAction("Details", new { id = circle.BetCircleID });
            }


            //si on est là on réaffiche la la page pour expliquer pkoi le user ne peut pas rejoindre le cercle
            return View("JoinCircle", vm);
        }


        /*public ActionResult AddUserToCircle(int UserID, int CircleID)
        {
            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            BetCircle betSet = circleService.GetForAdministration(CircleID, user);


            circleService.AddUserToCircle(UserID, betSet);


            return Json(user.UserID);
        }*/

    
    }
}

ParisEntreAmis/Controllers/BetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParisEntreAmis.Models;
using ParisEntreAmis.Service;


namespace ParisEntreAmis.Controllers
{
    [Authorize]
    public class BetController : BaseController
    {
        private UserService userService = new UserService();

        private BetCircleService circleService = new BetCircleService();
        private BetService betService = new BetService();

        public BetController()
        {
            ViewBag.SaveSucess = false;

        }


        // public ActionResult Fix(int id)
        // {

        //    User user = userService.GetCurrentUser();

        //    if (user == null)
        //    {
        //        return HttpNotFound();
        //    }
            
        //    Bet bet = betService.GetForBetting(id, user);

        //    if (bet == null)
        //    {
        //        return HttpNotFound();
        //    }
            
        //    bet.DeadLine =  new DateTime (DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 9, 30, 0);
        //    betService.SaveChanges(bet);
        //    return View();

        //}

        public ActionResult Play(int id)
        {

            User user = userService.GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }
            
            Bet bet = betService.GetForBetting(id, user);

            if (bet == null)
            {
                return HttpNotFound();
            }


            
            BetPlayedEditModel vm = betService.InitBetPlayedEditModel(bet, user);

            return View(vm);

        }

        [HttpPost]
        public ActionResult Play(BetPlayedEditModel BetPlayedEditModel)
        {
            User user = userService.GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            //Get the bet to check the deadline
            Bet bet = betService.GetForBetting(BetPlayedEditModel.BetID, user);

            if (!betService.CheckIfUserCanPlay(bet, user))
            {
                return HttpNotFound();
            }

            betService.SaveBetPlayed(BetPlayedEditModel, user , bet);

            BetPlayedEditModel vm = betService.InitBetPlayedEditModel(bet, user);



            ViewBag.SaveSucess = true;

            return View(vm);
        }

        

    }
}

ParisEntreAmis/Controllers/MatchController.cs
using ParisEntreAmis.Models;
using ParisEntreAmis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ParisEntreAmis.Controllers
{
    public class MatchController : BaseController
    {


        private MatchService matchService = new MatchService();


        //
        // GET: /Match/


        [Authorize(Roles=Constants.ROLE_ADMIN)]
        public ActionResult Edit(int id)
        {

            Match match = matchService.GetById(id);

            MatchEditModel em = matchService.InitMatchEditModel(match);

            return View(em);
        }
        
        [Authorize(Roles = Constants.ROLE_ADMIN)]
        [HttpPost]
        public ActionResult Edit(MatchEditModel em, string scorersJson)
        {
            var scorers = new JavaScriptSerializer().Deserialize<IEnumerable<MatchGoal>>(scorersJson);


            //On recupere le match de la BDD pour le modifier
            Match match = matchService.GetById(em.MatchID);


            match.ScoreAwayTeam = em.ScoreAwayTeam;
            match.ScoreHomeTeam = em.ScoreHomeTeam;


            matchService.replaceScorers(match, scorers.ToList());
            matchService.saveChanges(match);

            ///
            /// TODO: CALL AJAX POUR METTRE UN CHARGEMENT EN PLACE
            /// POURRA PRENDRE BCP DE TEMPS
            /// CALCUL DES SCORES
            ///
            matchService.ComputeBetsForMatch(match);

            em = matchService.InitMatchEditModel(match);
            
            return View(em);
        }

        public ActionResult NextMatchs()
        {


            List<Match> matchs = matchService.GetMatchsAfterDate(new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day),100);

            return View(matchs);

        }



    }
}

ParisEntreAmis/Views/Bet/Play.cshtml
@model ParisEntreAmis.Models.BetPlayedEditModel

@{
    ViewBag.Title = "Mise en place du pronostic";
}




<ol class="breadcrumb breadcrumb-large">
    <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a></li>
    <li><a href="@Url.Action("Details", "BetCircle", new { id=@Model.Bet.CircleID })">@Model.Bet.Circle.Name</a></li>
    <li class="active">@Model.Bet.Match.HomeTeam.Name - @Model.Bet.Match.AwayTeam.Name</li>
</ol>


@if (ViewBag.SaveSucess)
{
    <div class="alert alert-success">Sauvegarde effectuée avec succès</div>
}


@if (! Model.Bet.CalculateNormalScore)
{
    <div class="alert alert-danger">Seul le résultat du match (1/N/2) sera pris en compte dans le calcul des points. Autrement dit Il suffit juste de renseigner un score pour indiquer 1/N/2 !!!</div>
}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">La rencontre:</h3>
  </div>
  <div class="panel-body">
    
      @if (Model.Bet.Match.ScoreAwayTeam != null)//match terminé
      {
          
          <table>
              <tr>
                  <td class="text-center">@Model.Bet.Match.HomeTeam.Name <b>@Model.Bet.Match.ScoreHomeTeam </b></td>
                  <td class="text-center"> - </td>
                  <td class="text-center"><b>@Model.Bet.Match.ScoreAwayTeam</b> @Model.Bet.Match.AwayTeam.Name</td>
              </tr>
              <tr>
                  <td>
                      <ul>
                          @foreach (var scorer in @Model.Bet.Match.MatchGoals.Where(p=>p.TeamID == @Model.Bet.Match.HomeTeam.TeamID))
                          {
                              <li>@scorer.Player.Name @scorer.Player.FirstName</li>
                          }
                      </ul>

                  </td>
                  <td></td>
                  <td>
                      <ul>
                          @foreach (var scorer in @Model.Bet.Match.MatchGoals.Where(p=>p.TeamID == @Model.Bet.Match.AwayTeam.TeamID))
                          {
                              <li>@scorer.Player.Name @scorer.Player.FirstName</li>
                          }
                      </ul>

                  </td>
              </tr>
          </table>
          

      }
      else
      {
        <span>@Model.Bet.Match.HomeTeam.Name - @Model.Bet.Match.AwayTeam.Name</span>
      }


      <br /><br />
      <i>Date de la rencontre: @Model.Bet.Match.Date</i>
      <br /><br />


       @if (@Model.Bet.IsClosed && !Model.Bet.Match.IsFinished)
        {
            <div class="alert alert-danger">Les pronostics sont clos! Les scores seront calculés lorsque le résultats du match sera disponible.</div>
        }
      <br />
      
      @if (User.IsInRole(ParisEntreAmis.Constants.ROLE_ADMIN))
      {
          @Html.ActionLink("Modifier le score de la rencontre", "Edit", "Match", new { id=Model.Bet.MatchID },null )
      }
      

  </div>
</div>


@if (Model.Bet.IsClosed)
{        
    <div class="row">    

        <div class="col-md-6">
            <div class="panel panel-success">
                  <div class="panel-heading">
                    <h3 class="panel-title">Pronostic mis en place:</h3>
                  </div>
                  <div class="panel-body">

                      @if(Model.CurrentUserDidNotPlayed)
                      {
                          <b>Vous n'avez pas joué</b>
                      }
                      else
                      {                            
                          @Model.Bet.Match.HomeTeam.Name  <b> @Model.ScoreHomeTeam - @Model.ScoreAwayTeam</b>  @Model.Bet.Match.AwayTeam.Name

                          <br />
                          <div>
                          <b>Buteur: </b>
                          
                          @if(Model.Scorer != null)
                          {
                             <i> @Model.Scorer.Name @Model.Scorer.FirstName</i><span> ( @Model.Scorer.Team.Name )</span>
                          }else{
                              <span>aucun</span>
                          }
                          </div>
                          
                          
                      }                   

                  </div>
            </div>
        </div>  

        <div class="col-md-6">

            <div class="panel panel-success">
                  <div class="panel-heading">
                    <h3 class="panel-title">Côtes:</h3>
                  </div>
                  <div class="panel-body">

                      @if ( Model.Bet.CalculateNormalScore)
                      {
                        <span>    
                          Victoire de  @Model.Bet.Match.HomeTeam.Name: @Model.BetOdds.OddHomeTeamWin<br />
                          Match nul: @Model.BetOdds.OddDrawGame<br />
                          Victoire de  @Model.Bet.Match.AwayTeam.Name: @Model.BetOdds.OddAwayTeamWin
                        </span>
                      }
                      else
                      {
                          <span>
                          Donne +1 point en cas de résultat juste !
                        </span>
                      }


                  </div>
            </div>            

        </div>

    </div>
    
    
    
    <div class="row">
        
        <div class="col-md-12">

            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Les pronostics des membres du cercle:</h3>
                </div>
            <div class="panel-body">

                @if (!Model.Bet.Match.IsFinished)
                {
                    <b>Les points seront calculés lorsque le résultat du match sera disponible</b>
                }

                <table class="table table-striped table-condensed">

                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Score</th>
                        <th>Pronostic
                            <br />
                            @Model.Bet.Match.HomeTeam.Name - @Model.Bet.Match.AwayTeam.Name

                        </th>
                        <th>Buteur</th>
                        @if (Model.Bet.Match.IsFinished)
                        {
                            <th>Points résultat</th>
                            <th>Points score</th>
                            <th>Points buteur</th>
                            <th>Points total rencontre</th>
                            <th><i class="fa fa-coffee"></i> Café ?</th>
                        }
                    </tr>

                    @{int i = 1;}
                    @foreach (var bet in Model.UsersScoreBoardWithBet)
                    {
                        
                        <tr>
                            <td>
                                @i
                            </td>
                            <td>
                                <b> @bet.Name</b>
                            </td>
                            <td>
                                @bet.Score
                            </td>
                            <td>

                                @if (bet.BetPlayedInCurrentContext.HasNotPlayed)
                                {
                                    <b>pas joué</b>
                                }
                                else
                                {                                   
                                   
                                    <b> @bet.BetPlayedInCurrentContext.ScoreHomeTeam - @bet.BetPlayedInCurrentContext.ScoreAwayTeam</b>                                    
                                }
                            </td>
                            <td>
                                @if ( ! bet.BetPlayedInCurrentContext.HasNotPlayed)
                                {
                                    <b><i>@bet.BetPlayedInCurrentContext.ScorerName @bet.BetPlayedInCurrentContext.ScorerFirstName</i></b> 
                                }
                            </td> 
                                    
                            @if (Model.Bet.Match.IsFinished)
                            {
                                <td>
                                    @bet.BetPlayedInCurrentContext.PointsResult
                                </td>
                                <td>
                                    @bet.BetPlayedInCurrentContext.PointsScore
                                </td>
                                <td>
                                    @bet.BetPlayedInCurrentContext.PointsScorer
                                </td>
                                <td>
                                    <b>@bet.BetPlayedInCurrentContext.Total</b>
                                </td>
                                <td>
                                    @if (bet.BetPlayedInCurrentContext.IsLooser)
                                    {
                                        <i class="fa fa-coffee fa-2x"></i>
                                    }
                                </td>
                            }
                                                                       
                        </tr>
                        i++;

                    }
                </table>
                    
            </div>
        </div>
        </div>
    </div>
}
else
{
    

    using (Html.BeginForm())
    {

        @Html.HiddenFor(model=>model.BetID)
        
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">pronostic mis en place:</h3>
          </div>
          <div class="panel-body">
    
              

                @if (! Model.Bet.CalculateNormalScore)
                {
                    <div class="alert alert-danger">Seul le résultat du match (1/N/2) sera pris en compte dans le calcul des points. Autrement dit Il suffit juste de renseigner un score pour indiquer 1/N/2 !!!</div>
                }

                <i>Date limite: @Model.Bet.DeadLine.AddHours(1) (Après cette date il ne sera plus possible de modifier le pronostic)</i>
                <br />

                @Model.Bet.Match.HomeTeam.Name  @Html.EditorFor(model=>model.ScoreHomeTeam)  -  @Html.EditorFor(model=>model.ScoreAwayTeam)  @Model.Bet.Match.AwayTeam.Name

              <br />
              <br />
              <b>Buteur:</b>

              <select name="ScorerID">
                  <option></option>
                  <optgroup label="@Model.Bet.Match.HomeTeam.Name"></optgroup>

                  @foreach (var p in @Model.PlayersHomeTeam)
                  {
                      string selected = "";

                      if (p.PlayerID == Model.ScorerID)
                      {
                          selected = "selected=\"selected\"";
                      }
                  
                      <option @selected value="@p.PlayerID">@p.FirstName @p.Name</option>
                  }

                  <optgroup label="@Model.Bet.Match.AwayTeam.Name"></optgroup>

                  @foreach (var p in @Model.PlayersAwayTeam)
                  {
                      string selected = "";

                      if (p.PlayerID == Model.ScorerID)
                      {
                          selected = "selected=\"selected\"";
                      }
                  
                      <option @selected value="@p.PlayerID">@p.FirstName @p.Name</option>
                  }


              </select>
          
          </div>
        </div>
        
        <input class="btn btn-success" type="submit" value="Sauvegarder">
        <br />
        <i>Il sera toujours possible de modifier le pari jusqu'à la date limite.</i>
      
    
    }
}