ParisEntreAmis/Models/ViewModel/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParisEntreAmis.Models
{
    public class HomeViewModel : LoginModel
    {

        

        public List<BetCircleViewModel> CirclesJoined { get; set; }


        public List<Match> LastMatchs { get; set; }

        public List<Match> NextMatchs { get; set; }

    }
}

ParisEntreAmis/Controllers/BetCircleController.cs
using ParisEntreAmis.Models;
using ParisEntreAmis.Repository;
using ParisEntreAmis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParisEntreAmis.Controllers
{
    [Authorize]
    public class BetCircleController : BaseController
    {

        private BetCircleService circleService = new BetCircleService();
        private BetService betService = new BetService();
        private MatchService matchService = new MatchService();


        //
        // GET: /BetCircle/

        public ActionResult Index()
        {
            
            return View(circleService.GetAll());
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BetCircle b)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    User usr =null;

                    var repo = new UserRepository();
                   
                    usr  = repo.GetByUsername(User.Identity.Name);
                    

                    if (usr == null)
                        throw new Exception("Bad user");

                    circleService.Create(b, usr);
                    return RedirectToAction("Edit", new { id = b.BetCircleID });
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("",ex.Message);

                }
            }


            return View(b);
        }

        public ActionResult Details(int id) 
        {
            User usr = null;

            var repo = new UserRepository();
           
            usr = repo.GetByUsername(User.Identity.Name);
           

            if (usr == null)
                throw new Exception("Bad user");

            BetCircle betSet = this.circleService.Get(id,usr);

            if (betSet == null)
            {
                return HttpNotFound();
            }


            var tokenGenerator = new Firebase.TokenGenerator("3BNGwIhvAPAfIJIZLANvdsiwgOuAR1lfQtnYORaE");
            var authPayload = new Dictionary<string, object>()
            {                
                { "Username" , usr.Username },
                { "circleID" , betSet.BetCircleID .ToString()}
            };

            string token = tokenGenerator.CreateToken(authPayload);

            ViewBag.firebaseToken = token;

            return View(this.circleService.InitBetCircleViewModel(betSet, usr));

        }


        public ActionResult Edit(int id)
        {
            User usr = null;

            var repo = new UserRepository();

            usr = repo.GetByUsername(User.Identity.Name);


            if (usr == null)
                throw new Exception("Bad user");

            BetCircle betSet = this.circleService.GetForAdministration(id, usr);

            if (betSet == null)
            {
                return HttpNotFound();
            }

            return View(this.circleService.InitEditModel(betSet));

        }

        public ActionResult DisplayBetsAvailableInCategory(int BetCircleID , string CodeCategory)
        {
            User usr = null;

            var repo = new UserRepository();

            usr = repo.GetByUsername(User.Identity.Name);

            BetCircle circle = this.circleService.GetForAdministration(BetCircleID, usr);
            if (circle == null)
            {
                return HttpNotFound();
            }


            BetsAvailableForCircleEditModel res = this.circleService.GetAvailableBetsInCategory(circle, CodeCategory);

            return PartialView("_AddBetToCircle", res);

        }


        //
        // GET: /Bet/

        public ActionResult AddMatchToCircle(int MatchID, int CircleID)
        {


            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }


            BetCircle betSet = circleService.GetForAdministration(CircleID, user);

            if (betSet == null)
            {
                return HttpNotFound();
            }


            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }

            Bet bet = betService.Create(match, betSet);

            return PartialView("_EditBetsInCircle", bet);
        }


        public ActionResult RemoveMatchFromCircle(int MatchID, int CircleID)
        {

            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            BetCircle betSet = circleService.GetForAdministration(CircleID, user);

            if (betSet == null)
            {
                return HttpNotFound();
            }

            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }


            int betIdDeleted = circleService.RemoveMatchFromCircle(match, betSet);


            return Json(betIdDeleted, JsonRequestBehavior.AllowGet);
        }


        public ActionResult RemoveBetFromCircle(int BetID, int MatchID)
        {
            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            Bet bet = betService.GetForAdministration(BetID, user);

            if (bet == null)
            {
                return HttpNotFound();
            }

            Match match = matchService.GetById(MatchID);

            if (match == null)
            {
                return HttpNotFound();
            }

            betService.Delete(bet);

            return Json(0, JsonRequestBehavior.AllowGet);
        }


        public ActionResult JoinCircle(string circleGuid)
        {
            User user = new UserService().GetCurrentUser();

            ConfirmJoinCircle vm = new ConfirmJoinCircle();

            BetCircle circle = this.circleService.GetCircleByGuid(circleGuid);

            if (circle == null)
            {
                return HttpNotFound();
            }

            vm.BetCircle = circle;
            vm.Status = this.circleService.DoesUserCanJoinCircle(circle, user);


            return View(vm);
        }

        public ActionResult ConfirmJoinCircle(string circleGuid)
        {
            
            User user = new UserService().GetCurrentUser();

            ConfirmJoinCircle vm = new ConfirmJoinCircle();

            BetCircle circle = this.circleService.GetCircleByGuid(circleGuid);

            if (circle == null)
            {
                return HttpNotFound();
            }

            vm.BetCircle = circle;
            vm.Status = this.circleService.DoesUserCanJoinCircle(circle, user);


            if (vm.Status == CanPeopleJoinCircle.Yes)
            {
                //on ajoute le user et on le redirige vers le cercle
                this.circleService.AddUserToCircle(user.UserID, circle);

                return RedirectToAction("Details", new { id = circle.BetCircleID });
            }


            //si on est là on réaffiche la la page pour expliquer pkoi le user ne peut pas rejoindre le cercle
            return View("JoinCircle", vm);
        }


        /*public ActionResult AddUserToCircle(int UserID, int CircleID)
        {
            User user = new UserService().GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            BetCircle betSet = circleService.GetForAdministration(CircleID, user);


            circleService.AddUserToCircle(UserID, betSet);


            return Json(user.UserID);
        }*/

    
    }
}

ParisEntreAmis/Controllers/BetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParisEntreAmis.Models;
using ParisEntreAmis.Service;


namespace ParisEntreAmis.Controllers
{
    [Authorize]
    public class BetController : BaseController
    {
        private UserService userService = new UserService();

        private BetCircleService circleService = new BetCircleService();
        private BetService betService = new BetService();

        public BetController()
        {
            ViewBag.SaveSucess = false;

        }


        // public ActionResult Fix(int id)
        // {

        //    User user = userService.GetCurrentUser();

        //    if (user == null)
        //    {
        //        return HttpNotFound();
        //    }
            
        //    Bet bet = betService.GetForBetting(id, user);

        //    if (bet == null)
        //    {
        //        return HttpNotFound();
        //    }
            
        //    bet.DeadLine =  new DateTime (DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 9, 30, 0);
        //    betService.SaveChanges(bet);
        //    return View();

        //}

        public ActionResult Play(int id)
        {

            User user = userService.GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }
            
            Bet bet = betService.GetForBetting(id, user);

            if (bet == null)
            {
                return HttpNotFound();
            }


            
            BetPlayedEditModel vm = betService.InitBetPlayedEditModel(bet, user);

            return View(vm);

        }

        [HttpPost]
        public ActionResult Play(BetPlayedEditModel BetPlayedEditModel)
        {
            User user = userService.GetCurrentUser();

            if (user == null)
            {
                return HttpNotFound();
            }

            //Get the bet to check the deadline
            Bet bet = betService.GetForBetting(BetPlayedEditModel.BetID, user);

            if (!betService.CheckIfUserCanPlay(bet, user))
            {
                return HttpNotFound();
            }

            betService.SaveBetPlayed(BetPlayedEditModel, user , bet);

            BetPlayedEditModel vm = betService.InitBetPlayedEditModel(bet, user);



            ViewBag.SaveSucess = true;

            return View(vm);
        }

        

    }
}

ParisEntreAmis/Controllers/HomeController.cs
using ParisEntreAmis.Filters;
using ParisEntreAmis.Models;
using ParisEntreAmis.Repository;
using ParisEntreAmis.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace ParisEntreAmis.Controllers
{
    public class HomeController : BaseController
    {
        private BetCircleService service = new BetCircleService();

        private MatchService matchService = new MatchService();

        public ActionResult Index()
        {

            
            
            //var u = repo.All.FirstOrDefault();
            

            HomeViewModel vm = new HomeViewModel();
            if (User.Identity.IsAuthenticated)
            {
                var repo = new UserRepository();    
                User usr = repo.GetByUsername(User.Identity.Name);
               
                if (usr == null)
                {
                    return RedirectToAction("Login", "Account");

                   // return HttpNotFound();
                }

                vm.CirclesJoined = service.GetCirclesForUser(usr);

            }


            vm.LastMatchs = matchService.GetMatchsBeforeDate(DateTime.Now);

            vm.NextMatchs = matchService.GetMatchsAfterDate(DateTime.Now);



            return View(vm);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Votre page de description d’application.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Votre page de contact.";

            return View();
        }
    }
}

ParisEntreAmis/Views/Home/About.cshtml
@{
    ViewBag.Title = "À propos de";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Indiquez des informations supplémentaires à l'aide de cette zone.
    </p>

    <p>
        Indiquez des informations supplémentaires à l'aide de cette zone.
    </p>

    <p>
        Indiquez des informations supplémentaires à l'aide de cette zone.
    </p>
</article>

<aside>
    <h3>Titre à part</h3>
    <p>
        Indiquez des informations supplémentaires à l'aide de cette zone.
    </p>
    <ul>
        <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
        <li>@Html.ActionLink("À propos de", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

ParisEntreAmis/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Téléphone</h3>
    </header>
    <p>
        <span class="label">Principal :</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">En dehors des heures d'ouverture :</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Adresse de messagerie </h3>
    </header>
    <p>
        <span class="label">Support :</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing :</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">Général :</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Adresse</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

ParisEntreAmis/Views/Home/Index.cshtml
@model ParisEntreAmis.Models.HomeViewModel

@{
    ViewBag.Title = "Pronostics Entre Amis";
}

<div class="row">
  <div class="col-md-4">

  


    @if (Request.IsAuthenticated)
    {

        <a href="@Url.Action("Create","BetCircle")" class="btn btn-success btn-lg btn-block">Créér un nouveau cercle</a>
              <br />
    
        if (Model.CirclesJoined.Count > 0)
        {   
            <div class="list-group">
            
                @foreach (var item in Model.CirclesJoined)
                {
                    <a href="@Url.Action("Details","BetCircle",new{ id=@item.BetCircle.BetCircleID})" class="list-group-item" >
                         
                        <h4 class="list-group-item-heading"> @item.BetCircle.Name

                            <div class="pull-right"><span class="glyphicon glyphicon-log-in"></span></div>

                        </h4>
                                           
                    </a>
                           
                }

           </div>
           
        }
        else
        {
            <div class="alert alert-warning">
                <b>Bienvenue @User.Identity.Name!</b><br />
                 <b>Vous ne faites partie d'aucun cercles </b>
                     Créér votre propre cercle et invitez vos amis ou faites vous inviter!
            </div>           
        }
        
        <script src='https://cdn.firebase.com/v0/firebase.js'></script>
        
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Notifications</div>
            
           

            <div id="tableNotifications" class="list-group">
                <div id="loading">
                    <i>Chargement en cours...</i>
                </div>  
            </div>

        </div>
        
        <script>
            
            var myDataRef = new Firebase('https://kymic.firebaseio.com/notifications/@WebSecurity.CurrentUserId');
                

            //var AUTH_TOKEN = "@ViewBag.firebaseToken";

            // Log me in.
            /*myDataRef.auth(AUTH_TOKEN, function (error) {
                if (error) {
                    console.log("Login Failed!", error);
                } else {
                    console.log("Login Succeeded!");
                }
            });*/
            
            myDataRef.on('value', function (snapshot) {
                $("#loading").hide();
            });

            myDataRef.on('child_added', function (snapshot) {
                var message = snapshot.val();
                displayNotification(message.Title, message.Message, message.BetID);

                $("#loading").hide();
            });

            function displayNotification(title, message,betID) {
                var url = "@Url.Action("Play","Bet")/" + betID;
                $("<a href=\""+url+"\" class=\"list-group-item\"><b>" + title + "</b><br/>" + message + "</a>").prependTo($('#tableNotifications'));

                //$('#messagesDiv')[0].scrollTop = $('#messagesDiv')[0].scrollHeight;
            };
        </script>
    
    }
    else
    {
        
        <div class="well well-lg">

            <blockquote>
                <p>Pronostics Entre Amis est entièrement gratuit!</p>
            </blockquote>

            Défiez vos amis en pariant sur les résultats des matchs, les buteurs, les scores des plus grands championnats Européens<br />
            

        </div>
        
    
        <h2>Connectez vous pour commencer à jouer!</h2>
        
        using (Html.BeginForm("Login", "Account", FormMethod.Post, new {  @class = "form-vertical" , @role="form" }))
        {
            <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
            
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

        
            <div class="form-group">
                <label for="inputEmail3" class="control-label">Pseudo</label>
                
                 <input type="text" id="inputEmail3" class="form-control" name="UserName" placeholder="Pseudo">
                
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="control-label">Mot de passe</label>
                
                 <input id="inputPassword3" type="password" class="form-control" name="Password" placeholder="Password">
                
             </div>
            <div class="form-group">
                
                <div class="checkbox">
                    <label>
                         @Html.CheckBoxFor(m => m.RememberMe)
                         Se souvenir de moi
                    </label>
                </div>
               
            </div>
            <div class="form-group">
                
                <button type="submit" class="btn btn-primary btn-lg btn-block">Connexion</button>
                <a href="@Url.Action("Register","Account")" class="btn btn-default btn-lg btn-block">S'enregistrer</a>
                
            </div>
          
          
          
        
        
        
        }

    
    }

  </div>
  <div class="col-md-8">

      <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Derniers résultats</div>
          <div class="panel-body">
          </div>

            <table class="table">
            
           

                @foreach (var match in Model.LastMatchs)
                {
                    <tr>
                        <td>
                           <img src="@Url.Content("~/Images/flags/"+match.Country+".png")" />
                        </td>
                        <td>
                            @match.Date.ToShortDateString() @match.Date.ToShortTimeString()
                        </td>
                        <td>
                            @match.HomeTeam.Name

                            <br /><i>
                            @foreach (var scorer in @match.MatchGoals.Where(t=>t.TeamID==match.HomeTeam.TeamID))
                            {
                                @scorer.Player.FullName<br />
                            }
                            </i>
                        </td>

                        <td><b>@match.ScoreHomeTeam</b></td>
                        <td><b>@match.ScoreAwayTeam</b></td>
                        
                        <td>
                             @match.AwayTeam.Name

                             <br /><i>
                            @foreach (var scorer in @match.MatchGoals.Where(t=>t.TeamID==match.AwayTeam.TeamID))
                            {
                                @scorer.Player.FullName<br />
                            }
                            </i>

                        </td>
                       

                    </tr>
                }
            </table>
           
       </div>

      <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Prochaines rencontres</div>
          <div class="panel-body">
          </div>

            <table class="table">
            
           

                @foreach (var match in Model.NextMatchs)
                {
                    <tr>
                        <td>
                            <img src="@Url.Content("~/Images/flags/"+match.Country+".png")" />
                        </td>
                        <td>
                            @match.Date.ToShortDateString() @match.Date.ToShortTimeString()
                        </td>
                        <td>
                            @match.HomeTeam.Name

                          
                        </td>

                        <td></td>
                        <td></td>
                        
                        <td>
                             @match.AwayTeam.Name

                            

                        </td>
                       

                    </tr>
                }
            </table>
           
       </div>

  </div>
</div>